In [1]:
#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import openpyxl

In [2]:
df=pd.read_excel("fortune500.xlsx")
df.head()

   Year  Rank           Company  Revenue (in millions) Profit (in millions)
0  1955     1    General Motors                 9823.5                  806
1  1955     2       Exxon Mobil                 5661.4                584.8
2  1955     3        U.S. Steel                 3250.4                195.4
3  1955     4  General Electric                 2959.1                212.6
4  1955     5            Esmark                 2510.8                 19.1

# Q.EVALAUTE DESCRIPTIVE STATISTICS AND PROVIDE THE INFERENCES FROM CALCULATIONS W.R.T REVENUE

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29500 entries, 0 to 29499
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   29500 non-null  int64
 1   Rank                   29500 non-null  int64
 2   Company                29500 non-null  object
 3   Revenue (in millions)  29500 non-null  float64
 4   Profit (in millions)   29500 non-null  object
dtypes: float64(1), int64(2), object(2)
memory usage: 1.1+ MB

In [7]:
df.isnull().sum()

Year                     0
Rank                     0
Company                  0
Revenue (in millions)    0
Profit (in millions)     0
dtype: int64

1.No null values are present.

In [8]:
# df1=df.copy()
# df1.groupby('Company')['Revenue (in millions)'].sum()

Company
3Com                20348.3
3M                 452853.7
A-T-O                1302.7
A. Schulman          8312.6
A.G. Edwards         8488.7
                     ...
Zimmer Holdings     14800.1
Zions Bancorp        5718.4
Zions Bancorp.       6782.3
Zurn Industries       610.6
eBay                26735.7
Name: Revenue (in millions), Length: 2588, dtype: float64

In [10]:
df1.size

147500

In [11]:
df1.drop_duplicates()

,Year,Rank,Company,Revenue (in millions),Profit (in millions)
0,1955,1,General Motors,9823.5,806
1,1955,2,Exxon Mobil,5661.4,584.8
2,1955,3,U.S. Steel,3250.4,195.4
3,1955,4,General Electric,2959.1,212.6
4,1955,5,Esmark,2510.8,19.1
...,...,...,...,...,...
29495,2009,996,Tellabs,1729.0,-930.1
29496,2009,997,Administaff,1724.4,45.8
29497,2009,998,Sanderson Farms,1723.6,-43.1
29498,2009,999,MGIC Investment,1721.5,-518.9
29499,2009,1000,Career Education,1720.8,60.1